import { AppData } from "../../readers/get_app_data";
import { generateFile } from "../index";

const gen_gitignore_phoenix = async ({ LibDir, WebDir, AppNameSnake }: AppData) => {
  const filename = ".gitignore";
  
  // Phoenix lib app gitignore
  const libContent = `# The directory Mix will write compiled artifacts to.
/_build/

# If you run "mix test --cover", coverage assets end up here.
/cover/

# The directory Mix downloads your dependencies sources to.
/deps/

# Where 3rd-party dependencies like ExDoc output generated docs.
/doc/

# Ignore .fetch files in case you like to edit your project deps locally.
/.fetch

# If the VM crashes, it generates a dump, let's ignore it too.
erl_crash.dump

# Also ignore archive artifacts (built via "mix archive.build").
*.ez

# Temporary files, for example, from tests.
/tmp/

# TypeScript/Node.js dependencies
lib/typescript/node_modules/

# Ignore package tarball (built via "mix hex.build").
${AppNameSnake}-*.tar`;

  // Phoenix web app gitignore
  const webContent = `# The directory Mix will write compiled artifacts to.
/_build/

# If you run "mix test --cover", coverage assets end up here.
/cover/

# The directory Mix downloads your dependencies sources to.
/deps/

# Where 3rd-party dependencies like ExDoc output generated docs.
/doc/

# Ignore .fetch files in case you like to edit your project deps locally.
/.fetch

# If the VM crashes, it generates a dump, let's ignore it too.
erl_crash.dump

# Also ignore archive artifacts (built via "mix archive.build").
*.ez

# Temporary files, for example, from tests.
/tmp/

# Ignore package tarball (built via "mix hex.build").
${AppNameSnake}_web-*.tar

# Static assets (generated by build process)
priv/static/assets/`;

  return Promise.all([
    generateFile({ filename, dir: LibDir, content: libContent }, "gen_gitignore_phoenix_lib"),
    generateFile({ filename, dir: WebDir, content: webContent }, "gen_gitignore_phoenix_web")
  ]);
};

export { gen_gitignore_phoenix };
